#!/usr/bin/env python3
"""Build the Judgment Explorer's data bundle (M5.0).

Reads the preserved full-lifecycle JudgmentRecords in ``explorer/records/`` (real
records from the M3.1-C.1 verified run), resolves each record's cited evidence ids to
their semantic labels via the experiment fixtures, and writes a single self-contained
``explorer/data.js`` (``window.LYR_RECORDS = [...]``) that ``index.html`` loads with
no build step and no network.

    python explorer/build_data.py
"""
from __future__ import annotations

import glob
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
EXPERIMENTS = REPO / "experiments"

DOMAIN_TITLES = {
    "experiment-001-memoir": "Memoir",
    "experiment-002-meeting": "Meeting notes",
    "experiment-003-financial-report": "Financial report",
    "experiment-004-git-history": "Git history",
}


def _semantic_map(domain: str) -> dict:
    sys.path.insert(0, str(EXPERIMENTS))
    from harness import load_records, to_semantic_nodes  # type: ignore
    return {n.id: {"kind": n.kind, "label": n.label}
            for n in to_semantic_nodes(load_records(EXPERIMENTS / domain))}


def _enrich(rec: dict, smap: dict, domain: str) -> dict:
    mi, ea = rec["model_intent"], rec["final_engine_action"]
    ver = rec.get("verification")

    def label(sid: str) -> dict:
        return smap.get(sid, {"kind": "?", "label": sid})

    groups = [
        {"same_observation": g.get("same_observation", False),
         "note": g.get("note", ""),
         "members": [label(s)["label"] for s in g.get("semantic_ids", [])]}
        for g in rec.get("evidence_groups", [])
    ]
    return {
        "id": rec["judgment_id"],
        "domain": domain,
        "domain_title": DOMAIN_TITLES.get(domain, domain),
        "evidence": [label(s) for s in mi.get("evidence", [])],
        "evidence_groups": groups,
        "builder": {
            "operation": mi["operation"], "kind": mi["kind"], "statement": mi["statement"],
            "rationale": mi.get("rationale", ""), "counter_evidence": mi.get("counter_evidence", ""),
            "confidence": mi.get("confidence"),
        },
        "verifier": None if not ver else {
            "decision": ver.get("decision"), "status": ver.get("status"),
            "rationale": ver.get("rationale", ""), "confidence": ver.get("confidence"),
            "error_reason": ver.get("error_reason"),
        },
        "engine": {
            "operation": ea["operation"], "identity": ea.get("identity"),
            "version": ea.get("version"), "node_id": ea.get("node_id"),
            "rejection_reason": ea.get("rejection_reason"),
        },
        "committed": ea.get("node_id") is not None,
        "model": rec.get("model_config", {}).get("model", "?"),
    }


def main() -> None:
    records = []
    smaps: dict[str, dict] = {}
    for path in sorted(glob.glob(str(HERE / "records" / "*.json"))):
        rec = json.loads(Path(path).read_text())
        domain = Path(path).stem.split("__", 1)[0]
        smaps.setdefault(domain, _semantic_map(domain))
        records.append(_enrich(rec, smaps[domain], domain))

    # committed durables first, then rejects, then builder-NO_OPs — a good reading order
    order = {"KEEP": 0, "UNSURE": 1, "REJECT": 2, None: 3}
    records.sort(key=lambda r: (order.get(r["verifier"]["decision"] if r["verifier"] else None, 3),
                                r["domain"]))

    out = HERE / "data.js"
    out.write_text("// Generated by build_data.py — real JudgmentRecords from the M3.1-C.1 verified run.\n"
                   "window.LYR_RECORDS = " + json.dumps(records, indent=2, ensure_ascii=False) + ";\n")
    print(f"wrote {out.relative_to(REPO)} — {len(records)} judgments")


if __name__ == "__main__":
    main()
