// Generated by build_data.py — real JudgmentRecords from the M3.1-C.1 verified run.
window.LYR_RECORDS = [
  {
    "id": "jdg_01KZ0JYSNDXPWCFKXAPTR6N832",
    "domain": "experiment-001-memoir",
    "domain_title": "Memoir",
    "evidence": [
      {
        "kind": "event",
        "label": "Left a fast-growing startup in 2012 to care for her husband through his cancer treatment."
      },
      {
        "kind": "event",
        "label": "Turned down an overseas transfer to Singapore in 2005 so the children could stay in the same school."
      },
      {
        "kind": "event",
        "label": "Declined a promotion to regional director in 1998 to stay in her hometown near her aging parents."
      }
    ],
    "evidence_groups": [],
    "builder": {
      "operation": "ADD",
      "kind": "preference",
      "statement": "Consistently prioritizes family commitments over career advancement.",
      "rationale": "The pattern across multiple events indicates a strong and consistent preference for prioritizing family over career opportunities.",
      "counter_evidence": "",
      "confidence": 0.9
    },
    "verifier": {
      "decision": "KEEP",
      "status": "SUCCESS",
      "rationale": "The consistent pattern of prioritizing family commitments over career advancement is a significant and lasting preference demonstrated through multiple decisions across different life stages.",
      "confidence": 0.95,
      "error_reason": null
    },
    "engine": {
      "operation": "ADD",
      "identity": "idn_4a14ecd8eaeb",
      "version": 1,
      "node_id": "dur_8a2a95b84715",
      "rejection_reason": null
    },
    "committed": true,
    "model": "gpt-4o"
  },
  {
    "id": "jdg_01KZ0JYW54KB29XHC8Z5B2QBG3",
    "domain": "experiment-001-memoir",
    "domain_title": "Memoir",
    "evidence": [
      {
        "kind": "relationship",
        "label": "Wrote to her sister in Poland every single week for thirty years."
      },
      {
        "kind": "event",
        "label": "Emigrated from Poland to Canada in 1990, leaving her parents and siblings behind, never to live in the same country as them again."
      }
    ],
    "evidence_groups": [
      {
        "same_observation": true,
        "note": "Emigration event indicating geographical separation.",
        "members": [
          "Emigrated from Poland to Canada in 1990, leaving her parents and siblings behind, never to live in the same country as them again."
        ]
      },
      {
        "same_observation": true,
        "note": "Consistent communication pattern over thirty years.",
        "members": [
          "Wrote to her sister in Poland every single week for thirty years."
        ]
      }
    ],
    "builder": {
      "operation": "ADD",
      "kind": "pattern",
      "statement": "Maintained a long-distance relationship with her sister in Poland for thirty years through weekly letters, after emigrating to Canada in 1990.",
      "rationale": "The record shows a durable pattern of maintaining communication over a long period, emphasizing a commitment to familial connection despite geographical separation.",
      "counter_evidence": "",
      "confidence": 0.9
    },
    "verifier": {
      "decision": "KEEP",
      "status": "SUCCESS",
      "rationale": "The proposed memory represents a significant and lasting pattern of maintaining a long-distance familial relationship over an extended period, illustrating a persistent and meaningful commitment.",
      "confidence": 0.9,
      "error_reason": null
    },
    "engine": {
      "operation": "ADD",
      "identity": "idn_a522a09d4ed2",
      "version": 1,
      "node_id": "dur_a3b2bfa83c5d",
      "rejection_reason": null
    },
    "committed": true,
    "model": "gpt-4o"
  },
  {
    "id": "jdg_01KZ0JZ3RCXJDC148GHYM09R4J",
    "domain": "experiment-001-memoir",
    "domain_title": "Memoir",
    "evidence": [
      {
        "kind": "event",
        "label": "In her thirties she kept all savings in cash and refused to invest, fearing loss."
      },
      {
        "kind": "event",
        "label": "In her sixties she invested a large share of her retirement fund in her nephew's unproven restaurant venture."
      }
    ],
    "evidence_groups": [
      {
        "same_observation": false,
        "note": "Her decision to keep all savings in cash during her thirties demonstrates a preference for financial security due to fear of loss.",
        "members": [
          "In her thirties she kept all savings in cash and refused to invest, fearing loss."
        ]
      },
      {
        "same_observation": false,
        "note": "Her investment in an unproven business in her sixties shows a shift towards high-risk financial decisions.",
        "members": [
          "In her sixties she invested a large share of her retirement fund in her nephew's unproven restaurant venture."
        ]
      }
    ],
    "builder": {
      "operation": "ADD",
      "kind": "pattern",
      "statement": "She has shown a pattern of making high-risk financial decisions at different stages of her life.",
      "rationale": "The two records show a shift from extreme caution to high-risk financial behavior, suggesting a durable pattern of changing financial strategies.",
      "counter_evidence": "",
      "confidence": 0.7
    },
    "verifier": {
      "decision": "KEEP",
      "status": "SUCCESS",
      "rationale": "The statement reflects a lasting pattern of behavior regarding financial decision-making that spans multiple decades, indicating a persistent characteristic.",
      "confidence": 0.8,
      "error_reason": null
    },
    "engine": {
      "operation": "ADD",
      "identity": "idn_c8c3a4adf306",
      "version": 1,
      "node_id": "dur_762bdabbb3f2",
      "rejection_reason": null
    },
    "committed": true,
    "model": "gpt-4o"
  },
  {
    "id": "jdg_01KZ0JZ8NB5QEAHE70WB13W3XJ",
    "domain": "experiment-002-meeting",
    "domain_title": "Meeting notes",
    "evidence": [
      {
        "kind": "event",
        "label": "The team decided to sunset the legacy billing API by Q3 2026."
      }
    ],
    "evidence_groups": [
      {
        "same_observation": true,
        "note": "Reconfirmation of the decision to retire the legacy billing API.",
        "members": [
          "Reconfirmed the decision to retire the legacy billing API before Q3."
        ]
      }
    ],
    "builder": {
      "operation": "ADD",
      "kind": "decision",
      "statement": "The team has decided to sunset the legacy billing API by Q3 2026.",
      "rationale": "The decision to sunset the legacy billing API is a significant event with a timeline (Q3 2026) that constitutes a durable claim as it is an established decision with implications for future planning.",
      "counter_evidence": "",
      "confidence": 0.9
    },
    "verifier": {
      "decision": "KEEP",
      "status": "SUCCESS",
      "rationale": "The decision to sunset the legacy billing API by Q3 2026 is a significant and lasting decision that will likely have long-term implications for the team's operations and strategy.",
      "confidence": 0.9,
      "error_reason": null
    },
    "engine": {
      "operation": "ADD",
      "identity": "idn_3ce98fb0db7b",
      "version": 1,
      "node_id": "dur_117fbb04ba6e",
      "rejection_reason": null
    },
    "committed": true,
    "model": "gpt-4o"
  },
  {
    "id": "jdg_01KZ0JZBBM64MWZJKQZV5R4RP9",
    "domain": "experiment-002-meeting",
    "domain_title": "Meeting notes",
    "evidence": [
      {
        "kind": "event",
        "label": "Reversed the earlier Postgres decision and chose DynamoDB for the new services after load testing."
      },
      {
        "kind": "event",
        "label": "Agreed to standardize new services on Postgres."
      }
    ],
    "evidence_groups": [
      {
        "same_observation": false,
        "note": "Event 0 was reversed by event 1.",
        "members": [
          "Agreed to standardize new services on Postgres.",
          "Reversed the earlier Postgres decision and chose DynamoDB for the new services after load testing."
        ]
      }
    ],
    "builder": {
      "operation": "ADD",
      "kind": "decision",
      "statement": "The decision to standardize on Postgres for new services was reversed in favor of DynamoDB after load testing.",
      "rationale": "The two events combined highlight a significant decision change that reflects an outcome of evaluation, making it a durable knowledge worth keeping.",
      "counter_evidence": "The initial decision was not stable and has been explicitly reversed.",
      "confidence": 0.9
    },
    "verifier": {
      "decision": "KEEP",
      "status": "SUCCESS",
      "rationale": "The decision to standardize on a specific database technology for new services represents a significant and durable change in strategic direction, reflecting long-term architectural planning.",
      "confidence": 0.9,
      "error_reason": null
    },
    "engine": {
      "operation": "ADD",
      "identity": "idn_44749bc8d33f",
      "version": 1,
      "node_id": "dur_86385f914fdf",
      "rejection_reason": null
    },
    "committed": true,
    "model": "gpt-4o"
  },
  {
    "id": "jdg_01KZ0JZEFKSYF0F73XSWQJKH66",
    "domain": "experiment-002-meeting",
    "domain_title": "Meeting notes",
    "evidence": [
      {
        "kind": "event",
        "label": "Flaky CI on the payments suite blocked the release again."
      },
      {
        "kind": "event",
        "label": "Payments CI flakiness raised as a recurring release blocker."
      },
      {
        "kind": "event",
        "label": "Flaky CI on the payments suite came up as a blocker once more."
      }
    ],
    "evidence_groups": [
      {
        "same_observation": true,
        "note": "Both records 0 and 1 describe the same event of CI flakiness blocking the release.",
        "members": [
          "Flaky CI on the payments suite blocked the release again.",
          "Flaky CI on the payments suite came up as a blocker once more."
        ]
      }
    ],
    "builder": {
      "operation": "ADD",
      "kind": "pattern",
      "statement": "Flaky CI on the payments suite is a recurring release blocker.",
      "rationale": "The consistent theme across multiple records indicates that issues with CI for the payments suite repeatedly block releases, suggesting a problematic pattern worth noting.",
      "counter_evidence": "",
      "confidence": 0.85
    },
    "verifier": {
      "decision": "KEEP",
      "status": "SUCCESS",
      "rationale": "The statement identifies a persistent pattern where flaky CI on the payments suite acts as a recurring release blocker, suggesting a significant and lasting issue that impacts the release process.",
      "confidence": 0.9,
      "error_reason": null
    },
    "engine": {
      "operation": "ADD",
      "identity": "idn_8f468e5878fd",
      "version": 1,
      "node_id": "dur_1452e0789bed",
      "rejection_reason": null
    },
    "committed": true,
    "model": "gpt-4o"
  },
  {
    "id": "jdg_01KZ0JZKHVSQZFXBFX006BC9TE",
    "domain": "experiment-002-meeting",
    "domain_title": "Meeting notes",
    "evidence": [
      {
        "kind": "event",
        "label": "Hired a second SRE to own on-call rotation."
      }
    ],
    "evidence_groups": [
      {
        "same_observation": true,
        "note": "The hiring of a second SRE is a singular event indicating a decision to manage on-call rotation more effectively.",
        "members": [
          "Hired a second SRE to own on-call rotation."
        ]
      }
    ],
    "builder": {
      "operation": "ADD",
      "kind": "decision",
      "statement": "The organization has hired a second Site Reliability Engineer (SRE) to handle the on-call rotation, suggesting a growth in the team or an increased focus on operational reliability.",
      "rationale": "The hiring of additional personnel, especially for specialized roles such as SRE, usually reflects a strategic decision about team size or focus. This decision can have long-term implications for the team's operation and capabilities.",
      "counter_evidence": "",
      "confidence": 0.8
    },
    "verifier": {
      "decision": "KEEP",
      "status": "SUCCESS",
      "rationale": "The hiring of a second SRE is a significant decision indicating a growth in the team or an increased focus on operational reliability, which is likely to have a lasting impact on the organization's structure and priorities.",
      "confidence": 0.8,
      "error_reason": null
    },
    "engine": {
      "operation": "ADD",
      "identity": "idn_cf116ac835b7",
      "version": 1,
      "node_id": "dur_6822f6df2d2a",
      "rejection_reason": null
    },
    "committed": true,
    "model": "gpt-4o"
  },
  {
    "id": "jdg_01KZ0JZRXE35A9K98QSTJG6Q3S",
    "domain": "experiment-003-financial-report",
    "domain_title": "Financial report",
    "evidence": [
      {
        "kind": "event",
        "label": "The Northwind acquisition closed in the second quarter for approximately $2.1 billion."
      },
      {
        "kind": "event",
        "label": "Acquired competitor Northwind Analytics for $2.1B in Q2 2025."
      }
    ],
    "evidence_groups": [
      {
        "same_observation": true,
        "note": "Both records describe the acquisition of Northwind Analytics for $2.1 billion in Q2 2025.",
        "members": [
          "Acquired competitor Northwind Analytics for $2.1B in Q2 2025.",
          "The Northwind acquisition closed in the second quarter for approximately $2.1 billion."
        ]
      }
    ],
    "builder": {
      "operation": "ADD",
      "kind": "fact",
      "statement": "The company acquired Northwind Analytics for approximately $2.1 billion in Q2 2025.",
      "rationale": "The acquisition of Northwind Analytics is a significant event and thus, a durable fact, as both records independently corroborate this occurrence.",
      "counter_evidence": "",
      "confidence": 1.0
    },
    "verifier": {
      "decision": "KEEP",
      "status": "SUCCESS",
      "rationale": "The acquisition of Northwind Analytics for $2.1 billion is a significant fact that shows a major business decision and strategic expansion effort by the company, making it valuable long-term knowledge.",
      "confidence": 0.9,
      "error_reason": null
    },
    "engine": {
      "operation": "ADD",
      "identity": "idn_b2b047d1d254",
      "version": 1,
      "node_id": "dur_bb4cff4eb60d",
      "rejection_reason": null
    },
    "committed": true,
    "model": "gpt-4o"
  },
  {
    "id": "jdg_01KZ0JZVBJA7Y097XN5JGR9XRT",
    "domain": "experiment-003-financial-report",
    "domain_title": "Financial report",
    "evidence": [
      {
        "kind": "event",
        "label": "Raised the quarterly dividend for the 12th consecutive year."
      }
    ],
    "evidence_groups": [
      {
        "same_observation": true,
        "note": "Consistent dividend increase over 12 years supports the identified pattern.",
        "members": [
          "Raised the quarterly dividend for the 12th consecutive year."
        ]
      }
    ],
    "builder": {
      "operation": "ADD",
      "kind": "pattern",
      "statement": "The company has a pattern of raising its quarterly dividend consistently for 12 consecutive years.",
      "rationale": "This is a significant and consistent financial practice that demonstrates a durable pattern of shareholder value enhancement.",
      "counter_evidence": "",
      "confidence": 0.9
    },
    "verifier": {
      "decision": "KEEP",
      "status": "SUCCESS",
      "rationale": "A consistent pattern of raising dividends over 12 consecutive years is a significant financial indicator, representing stability and commitment to shareholders which is durable knowledge.",
      "confidence": 0.9,
      "error_reason": null
    },
    "engine": {
      "operation": "ADD",
      "identity": "idn_ea1008d8df7e",
      "version": 1,
      "node_id": "dur_b1248c44fe1a",
      "rejection_reason": null
    },
    "committed": true,
    "model": "gpt-4o"
  },
  {
    "id": "jdg_01KZ0K05HZPYB5A24KEFAHA4CW",
    "domain": "experiment-003-financial-report",
    "domain_title": "Financial report",
    "evidence": [
      {
        "kind": "event",
        "label": "Took a one-time $180M goodwill impairment on the 2019 Helios acquisition."
      }
    ],
    "evidence_groups": [
      {
        "same_observation": true,
        "note": "A significant financial event related to an acquisition.",
        "members": [
          "Took a one-time $180M goodwill impairment on the 2019 Helios acquisition."
        ]
      }
    ],
    "builder": {
      "operation": "ADD",
      "kind": "fact",
      "statement": "The company took a one-time $180M goodwill impairment on the 2019 Helios acquisition.",
      "rationale": "The goodwill impairment on the Helios acquisition is a significant financial event that represents a single, lasting impact on the company's financials, thus warranting durable memory.",
      "counter_evidence": "",
      "confidence": 0.9
    },
    "verifier": {
      "decision": "KEEP",
      "status": "SUCCESS",
      "rationale": "The $180M goodwill impairment on the 2019 Helios acquisition is a significant financial event for the company and could have implications for its financial history and future decisions. It reflects a major accounting decision related to the valuation of an acquisition, which is noteworthy in the company's long-term financial narrative.",
      "confidence": 0.9,
      "error_reason": null
    },
    "engine": {
      "operation": "ADD",
      "identity": "idn_e04066d05059",
      "version": 1,
      "node_id": "dur_0007f2ffd97f",
      "rejection_reason": null
    },
    "committed": true,
    "model": "gpt-4o"
  },
  {
    "id": "jdg_01KZ0K0AB7SZ49VFGQ9SY8D0KB",
    "domain": "experiment-004-git-history",
    "domain_title": "Git history",
    "evidence": [
      {
        "kind": "event",
        "label": "Migrated the public API from REST to gRPC."
      },
      {
        "kind": "event",
        "label": "Merge pull request #482: migrate public API from REST to gRPC."
      }
    ],
    "evidence_groups": [
      {
        "same_observation": true,
        "note": "Both records describe the same migration event.",
        "members": [
          "Migrated the public API from REST to gRPC.",
          "Merge pull request #482: migrate public API from REST to gRPC."
        ]
      }
    ],
    "builder": {
      "operation": "ADD",
      "kind": "decision",
      "statement": "Migrating the public API from REST to gRPC was a significant event.",
      "rationale": "The migration of a public API from REST to gRPC is a significant and likely impactful decision, warranting its addition as durable knowledge.",
      "counter_evidence": "",
      "confidence": 0.9
    },
    "verifier": {
      "decision": "KEEP",
      "status": "SUCCESS",
      "rationale": "Migrating a public API from REST to gRPC is a significant architectural decision that can have lasting impacts on system performance, development processes, and how clients interact with the service. This is a durable memory as it represents a significant event and decision.",
      "confidence": 0.9,
      "error_reason": null
    },
    "engine": {
      "operation": "ADD",
      "identity": "idn_6fd8c594cb0a",
      "version": 1,
      "node_id": "dur_e4d617949e3e",
      "rejection_reason": null
    },
    "committed": true,
    "model": "gpt-4o"
  },
  {
    "id": "jdg_01KZ0K0CXXZE9AJ7HE6CRMPZJB",
    "domain": "experiment-004-git-history",
    "domain_title": "Git history",
    "evidence": [
      {
        "kind": "event",
        "label": "Fixed a race condition in the auth token refresh."
      },
      {
        "kind": "event",
        "label": "Hardened auth middleware after a third session-handling regression."
      },
      {
        "kind": "event",
        "label": "Patched another auth session bug: tokens expiring early."
      }
    ],
    "evidence_groups": [
      {
        "same_observation": false,
        "note": "Multiple distinct events show a recurring issue with the auth system.",
        "members": [
          "Fixed a race condition in the auth token refresh.",
          "Patched another auth session bug: tokens expiring early.",
          "Hardened auth middleware after a third session-handling regression."
        ]
      }
    ],
    "builder": {
      "operation": "ADD",
      "kind": "pattern",
      "statement": "Auth middleware has recurrent issues with session handling and token expiration, requiring multiple patches.",
      "rationale": "The sequence of patches and regressions indicates a pattern of issues in the auth middleware, specifically related to session handling and token management.",
      "counter_evidence": "",
      "confidence": 0.9
    },
    "verifier": {
      "decision": "KEEP",
      "status": "SUCCESS",
      "rationale": "The statement identifies a recurring pattern of issues with session handling and token expiration in the auth middleware. This pattern is notable given the repeated need for patches and fixes, indicating a persistent issue that may impact system reliability and requires ongoing attention. As such, it represents genuine long-term knowledge worth keeping.",
      "confidence": 0.9,
      "error_reason": null
    },
    "engine": {
      "operation": "ADD",
      "identity": "idn_509718d384d8",
      "version": 1,
      "node_id": "dur_21e42e0f05c9",
      "rejection_reason": null
    },
    "committed": true,
    "model": "gpt-4o"
  },
  {
    "id": "jdg_01KZ0K0GYT1YFSPF6342AJ283F",
    "domain": "experiment-004-git-history",
    "domain_title": "Git history",
    "evidence": [
      {
        "kind": "event",
        "label": "Added a Redis cache in front of the product catalog."
      },
      {
        "kind": "event",
        "label": "Reverted the Redis catalog cache due to stale-read incidents."
      }
    ],
    "evidence_groups": [
      {
        "same_observation": false,
        "note": "The addition of a Redis cache was followed by its reversion due to issues with stale reads.",
        "members": [
          "Added a Redis cache in front of the product catalog.",
          "Reverted the Redis catalog cache due to stale-read incidents."
        ]
      }
    ],
    "builder": {
      "operation": "ADD",
      "kind": "lesson",
      "statement": "Implementing a Redis cache for the product catalog can lead to stale-read incidents.",
      "rationale": "The sequence of events shows a clear cause-and-effect relationship, providing a lesson on the potential issues with caching mechanisms.",
      "counter_evidence": "",
      "confidence": 0.8
    },
    "verifier": {
      "decision": "KEEP",
      "status": "SUCCESS",
      "rationale": "The proposed durable memory is a significant lesson about the potential consequences of using a Redis cache for the product catalog, specifically regarding stale-read incidents. This is a lasting lesson that can guide future decisions and implementations, making it worth retaining as long-term knowledge.",
      "confidence": 0.9,
      "error_reason": null
    },
    "engine": {
      "operation": "ADD",
      "identity": "idn_d848f04310e5",
      "version": 1,
      "node_id": "dur_81d58af477c2",
      "rejection_reason": null
    },
    "committed": true,
    "model": "gpt-4o"
  },
  {
    "id": "jdg_01KZ0JZ0KYVTP15FFSC31SGD1M",
    "domain": "experiment-001-memoir",
    "domain_title": "Memoir",
    "evidence": [
      {
        "kind": "event",
        "label": "Mentions her morning coffee ritual again while describing her writing desk."
      },
      {
        "kind": "event",
        "label": "Drank a cup of black coffee every morning before writing."
      }
    ],
    "evidence_groups": [
      {
        "same_observation": true,
        "note": "Both records describe the recurring pattern of drinking coffee in the morning before writing.",
        "members": [
          "Drank a cup of black coffee every morning before writing.",
          "Mentions her morning coffee ritual again while describing her writing desk."
        ]
      }
    ],
    "builder": {
      "operation": "ADD",
      "kind": "pattern",
      "statement": "Drinking a cup of black coffee is a part of her morning ritual before writing.",
      "rationale": "The pattern of drinking black coffee every morning before writing is reinforced by both new records and reflects a consistent behavior or ritual for her.",
      "counter_evidence": "",
      "confidence": 0.8
    },
    "verifier": {
      "decision": "REJECT",
      "status": "SUCCESS",
      "rationale": "The drinking of black coffee as a part of a morning ritual is a routine observation and does not constitute a significant long-term pattern or fact worth retaining as durable memory.",
      "confidence": 0.8,
      "error_reason": null
    },
    "engine": {
      "operation": "NO_OP",
      "identity": "idn_e5c6c387513a",
      "version": null,
      "node_id": null,
      "rejection_reason": "verifier REJECT: The drinking of black coffee as a part of a morning ritual is a routine observation and does not constitute a significant long-term pattern or fact worth retaining as durable memory."
    },
    "committed": false,
    "model": "gpt-4o"
  },
  {
    "id": "jdg_01KZ0JZYQMR33336CDY1D8C52M",
    "domain": "experiment-003-financial-report",
    "domain_title": "Financial report",
    "evidence": [
      {
        "kind": "event",
        "label": "Raised full-year revenue guidance to $9.4B at the Q1 2025 report."
      },
      {
        "kind": "event",
        "label": "Lowered full-year revenue guidance to $8.8B at the Q3 2025 report, citing softening enterprise demand."
      }
    ],
    "evidence_groups": [
      {
        "same_observation": false,
        "note": "Both records pertain to changes in fiscal year 2025 revenue guidance, providing a pattern of revision from initial optimism to a more conservative outlook.",
        "members": [
          "Raised full-year revenue guidance to $9.4B at the Q1 2025 report.",
          "Lowered full-year revenue guidance to $8.8B at the Q3 2025 report, citing softening enterprise demand."
        ]
      }
    ],
    "builder": {
      "operation": "ADD",
      "kind": "pattern",
      "statement": "In 2025, revenue guidance for the year was adjusted from $9.4B to $8.8B due to softening enterprise demand.",
      "rationale": "The records show a pattern in revenue guidance adjustments for 2025, capturing a shift in outlook due to changes in enterprise demand. This is a significant pattern relevant to stakeholders and strategic planning.",
      "counter_evidence": "The records are limited to the fiscal year 2025 and may not apply to other years.",
      "confidence": 0.8
    },
    "verifier": {
      "decision": "REJECT",
      "status": "SUCCESS",
      "rationale": "The adjustment of revenue guidance for 2025, while informative for the specific year, is a routine business recalibration and does not represent a durable pattern that is likely to have long-lasting significance beyond the fiscal year in question.",
      "confidence": 0.8,
      "error_reason": null
    },
    "engine": {
      "operation": "NO_OP",
      "identity": "idn_7d639f7a4054",
      "version": null,
      "node_id": null,
      "rejection_reason": "verifier REJECT: The adjustment of revenue guidance for 2025, while informative for the specific year, is a routine business recalibration and does not represent a durable pattern that is likely to have long-lasting significance beyond the fiscal year in question."
    },
    "committed": false,
    "model": "gpt-4o"
  },
  {
    "id": "jdg_01KZ0K018EB0MXYVZV680G596V",
    "domain": "experiment-003-financial-report",
    "domain_title": "Financial report",
    "evidence": [
      {
        "kind": "event",
        "label": "Cloud segment revenue grew 31% year over year in Q2 2025."
      }
    ],
    "evidence_groups": [
      {
        "same_observation": true,
        "note": "The record describes a specific growth in cloud segment revenue for Q2 2025.",
        "members": [
          "Cloud segment revenue grew 31% year over year in Q2 2025."
        ]
      }
    ],
    "builder": {
      "operation": "ADD",
      "kind": "fact",
      "statement": "Cloud segment revenue grew 31% year over year in Q2 2025.",
      "rationale": "The growth of cloud segment revenue by 31% year over year in Q2 2025 is a significant fact that can be considered a durable piece of knowledge worth retaining.",
      "counter_evidence": "",
      "confidence": 0.9
    },
    "verifier": {
      "decision": "REJECT",
      "status": "SUCCESS",
      "rationale": "The revenue growth figure for a specific quarterly period is a routine financial metric. While it may be significant in the short-term for business decisions, it does not constitute a lasting lesson or persistent pattern that warrants long-term memory retention.",
      "confidence": 0.9,
      "error_reason": null
    },
    "engine": {
      "operation": "NO_OP",
      "identity": "idn_8db38af033a4",
      "version": null,
      "node_id": null,
      "rejection_reason": "verifier REJECT: The revenue growth figure for a specific quarterly period is a routine financial metric. While it may be significant in the short-term for business decisions, it does not constitute a lasting lesson or persistent pattern that warrants long-term memory retention."
    },
    "committed": false,
    "model": "gpt-4o"
  },
  {
    "id": "jdg_01KZ0JZG3KJ2XHPP1HER4QCPM6",
    "domain": "experiment-002-meeting",
    "domain_title": "Meeting notes",
    "evidence": [],
    "evidence_groups": [
      {
        "same_observation": true,
        "note": "Both records describe people bringing donuts to a recurring Friday standup.",
        "members": [
          "Someone brought donuts to the Friday standup.",
          "Donuts again at Friday standup."
        ]
      }
    ],
    "builder": {
      "operation": "NO_OP",
      "kind": "lesson",
      "statement": "",
      "rationale": "The two records describe a trivial and recurring event that does not warrant a durable memory. There is no indication of significance leading to a lesson, decision, or pattern worth preserving long-term.",
      "counter_evidence": "The recurrence does not imply significance or change.",
      "confidence": 0.1
    },
    "verifier": null,
    "engine": {
      "operation": "NO_OP",
      "identity": null,
      "version": null,
      "node_id": null,
      "rejection_reason": null
    },
    "committed": false,
    "model": "gpt-4o"
  },
  {
    "id": "jdg_01KZ0K02RMSJNKTGMMVYX74W9J",
    "domain": "experiment-003-financial-report",
    "domain_title": "Financial report",
    "evidence": [],
    "evidence_groups": [
      {
        "same_observation": true,
        "note": "Both records represent the same event: quarterly rent expense.",
        "members": [
          "Recorded routine quarterly rent expense of $4.2M.",
          "Recorded routine quarterly rent expense of $4.2M."
        ]
      }
    ],
    "builder": {
      "operation": "NO_OP",
      "kind": "lesson",
      "statement": "",
      "rationale": "The records describe the same routine, recurring event and do not represent a durable memory worth retaining. Recurrent observations of routine expenses do not constitute a significant standalone fact or lesson.",
      "counter_evidence": "",
      "confidence": 0.9
    },
    "verifier": null,
    "engine": {
      "operation": "NO_OP",
      "identity": null,
      "version": null,
      "node_id": null,
      "rejection_reason": null
    },
    "committed": false,
    "model": "gpt-4o"
  },
  {
    "id": "jdg_01KZ0K0E9QCJQX9H4YZEVYAWR0",
    "domain": "experiment-004-git-history",
    "domain_title": "Git history",
    "evidence": [],
    "evidence_groups": [],
    "builder": {
      "operation": "NO_OP",
      "kind": "lesson",
      "statement": "",
      "rationale": "The version bumps from 2.3.1 to 2.3.3 represent routine and trivial changes that do not independently or collectively support a durable memory. Such events may be recurrent, but they do not convey a significant lesson, enduring pattern, or lasting fact.",
      "counter_evidence": "",
      "confidence": 0.9
    },
    "verifier": null,
    "engine": {
      "operation": "NO_OP",
      "identity": null,
      "version": null,
      "node_id": null,
      "rejection_reason": null
    },
    "committed": false,
    "model": "gpt-4o"
  }
];
